-- Rename InventoryEventType enum values to match spec
-- OPENING -> OPENING_STOCK, ADJUSTMENT -> ADJUSTED, CLOSING_CORRECTION -> CLOSING_STOCK
ALTER TYPE "InventoryEventType" RENAME VALUE 'OPENING' TO 'OPENING_STOCK';
ALTER TYPE "InventoryEventType" RENAME VALUE 'ADJUSTMENT' TO 'ADJUSTED';
ALTER TYPE "InventoryEventType" RENAME VALUE 'CLOSING_CORRECTION' TO 'CLOSING_STOCK';
