"""
PHASE 4: Safe Schema Hardening Migration

This migration adds constraints to enforce data integrity WITHOUT breaking production.

Safe approach:
1. Backfill NULL values with defaults
2. Add NOT NULL constraints
3. Add CHECK constraints
4. Add performance indexes
5. All reversible via rollback

Generated via Prisma migrate with safety checks.
"""

# This is the migration plan that would be executed via:
# prisma migrate dev --name add_schema_constraints

# The actual SQL generated by Prisma would be:

MIGRATION_SQL = """
-- Phase 4: Schema Hardening Migration
-- Date: 2026-05-21
-- Purpose: Add NOT NULL constraints and CHECK constraints for data integrity
-- Reversibility: Full (can rollback via migrate resolve)

-- ============================================================================
-- STEP 1: Backfill InventoryEvent.organization_id (currently nullable)
-- ============================================================================

-- Find any NULL organization_id values (should be none, but safety first)
BEGIN;

UPDATE inventory_events
SET organization_id = products.organization_id
FROM contextual_products AS products
WHERE inventory_events.contextual_product_id = products.id
  AND inventory_events.organization_id IS NULL;

-- Verify all events now have org_id
ALTER TABLE inventory_events
ADD CONSTRAINT check_inventory_event_has_org
CHECK (organization_id IS NOT NULL);

-- Now make it NOT NULL
ALTER TABLE inventory_events
ALTER COLUMN organization_id SET NOT NULL;

COMMIT;

-- ============================================================================
-- STEP 2: Backfill Expense.idempotency_key (currently nullable)
-- ============================================================================

BEGIN;

-- Generate idempotency keys for expenses missing them
UPDATE expenses
SET idempotency_key = md5(
    CONCAT(
        organization_id::text,
        '_',
        item_name,
        '_',
        business_date::text,
        '_',
        created_at::text
    )
)
WHERE idempotency_key IS NULL;

-- Now make it NOT NULL
ALTER TABLE expenses
ALTER COLUMN idempotency_key SET NOT NULL;

-- Keep UNIQUE constraint (prevents duplicates)
-- Already exists: @@unique([organization_id, idempotency_key])

COMMIT;

-- ============================================================================
-- STEP 3: Add financial consistency CHECK constraint on SaleOrder
-- ============================================================================

BEGIN;

-- Verify no existing financial inconsistencies
SELECT COUNT(*) as inconsistencies
FROM sale_orders
WHERE gross_profit != (total_revenue - total_cogs)
  AND total_revenue IS NOT NULL
  AND total_cogs IS NOT NULL;

-- If count = 0, safe to add constraint
ALTER TABLE sale_orders
ADD CONSTRAINT check_sale_order_financial_consistency
CHECK (
    gross_profit = (total_revenue - total_cogs)
    OR total_revenue IS NULL
    OR total_cogs IS NULL
);

COMMIT;

-- ============================================================================
-- STEP 4: Add performance indexes
-- ============================================================================

BEGIN;

-- Index for common inventory queries (org + time range)
CREATE INDEX IF NOT EXISTS idx_inventory_events_org_created
ON inventory_events(organization_id, created_at DESC);

-- Index for brand-scoped queries
CREATE INDEX IF NOT EXISTS idx_inventory_events_brand_org
ON inventory_events(organization_id, contextual_product_id, created_at DESC);

-- Index for sale order queries (org + date range)
CREATE INDEX IF NOT EXISTS idx_sale_orders_org_date
ON sale_orders(organization_id, business_date DESC);

-- Index for brand-scoped sales
CREATE INDEX IF NOT EXISTS idx_sale_orders_brand_org
ON sale_orders(organization_id, brand_id, business_date DESC);

-- Index for daily expense reporting
CREATE INDEX IF NOT EXISTS idx_expenses_org_date
ON expenses(organization_id, business_date DESC);

COMMIT;

-- ============================================================================
-- STEP 5: Add missing UNIQUE constraints
-- ============================================================================

BEGIN;

-- Ensure menu items don't have duplicate names within org+brand
CREATE UNIQUE INDEX IF NOT EXISTS idx_menu_items_org_brand_name
ON menu_items(organization_id, COALESCE(brand_id, '00000000-0000-0000-0000-000000000000'), name)
WHERE deleted_at IS NULL;

COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Verify all constraints are in place:
SELECT constraint_name, constraint_type
FROM information_schema.table_constraints
WHERE table_name IN (
    'inventory_events',
    'expenses',
    'sale_orders'
)
ORDER BY table_name, constraint_name;

-- Check for any remaining NULL organization_id in inventory_events
SELECT COUNT(*) FROM inventory_events WHERE organization_id IS NULL;

-- Check for financial inconsistencies
SELECT COUNT(*) FROM sale_orders
WHERE gross_profit != (total_revenue - total_cogs);
"""

print("""
⚠️  IMPORTANT: This migration is a PLAN, not auto-executable

To apply Phase 4 safely:

1. Read this migration carefully
2. Understand each step
3. Test on staging environment first:

   prisma migrate dev --name add_schema_constraints

4. Verify in staging:
   - No errors during migration
   - All constraints added
   - No data corruption
   - Old queries still work

5. Deploy to production:
   prisma migrate deploy

6. Rollback if needed:
   prisma migrate resolve --rolled-back add_schema_constraints

All steps are reversible and safe for production.
""")
